[pytest]
norecursedirs = migrations
addopts = --cache-clear --cov=app --cov-branch --cov-fail-under=100 --cov-report term --cov-report term-missing --cov-report xml:junitxml_report/coverage.xml -v --durations=5 --maxfail=3 --show-capture=all --failed-first -n auto
python_files = tests.py test_*.py
