line-length = 79
exclude = [
    "migrations",
    "env",
    "venv",
    ".tox",
    ".cache",
    ".git",
    "manage.py",
    "sil_recon/**/migrations/*",
    ".pytest_cache",
    "setup.py",
    "sil_recon/grpc",
    "_version.py"
]

[lint]

extend-select = [
    # flake8-comprehensions
    "C4",

    # flake8-simplify
    "SIM",

    # flake8-type-checking
    "TCH",

    # flake8-debugger
    "T10",

    # flake8-print
    "T20",

    # flake8-bugbear
    "B",

    # isort
    "I",

    # pycodestyle
    "E",

    # flake8-warnings
    "W",

    # Pyflakes
    "F",

    # missing docstrings
    "D1",

    # docstrings style (multi-line-summary-first-line)
    "D212",

    # type hints and checks
    "ANN",
]
fixable = ["ALL"]

[lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 10.
max-complexity = 10

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[lint.per-file-ignores]
# Ignore ANN201 and ANN101 for test files
"tests/*.py" = ["ANN201", "ANN101", "ANN001"]
