[tox]
requires =
    tox>=4.20.0
env_list = lint, test, package, publish


[testenv]
basepython = 
    py3.12: python3.12
whitelist_externals = sh
allowlist_externals = make, coverage
passenv =
    SECRET_KEY
    DB_NAME
    DB_PORT
    DB_HOST
    DB_USER
    DB_PASSWORD
setenv =
    DJANGO_SETTINGS_MODULE = tests.config.settings


[testenv:lint]
description = checks linters and types
depends = testenv
deps =
  -r requirements/dev.txt
commands =
    make lint
    make type_check


[testenv:test]
description = runs tests
depends = testenv
deps =
  -r requirements/test.txt
commands =
    coverage erase
    make test


[testenv:package]
description = build the library
commands =
    python -c "import shutil; shutil.rmtree('dist', ignore_errors=True)"
    python -m build
depends = testenv
deps =
    build==1.2.2
skip_install = true


[testenv:publish]
commands =
    twine upload --non-interactive -r slade --verbose dist/*
depends = package
deps =
    twine==6.1.0
description = publish to pypi
skip_install = true
